version: '3.3'
services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - ics_network
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=odoo@eazytraining.fr'
            - 'PGADMIN_DEFAULT_PASSWORD=odoo_pgadmin_password'
        ports:
            - "5050:80"
        volumes:
            - ${PWD}/servers.json:/pgadmin4/servers.json
            - 'pgadmin_data:/var/lib/pgadmin'
    ic-webapp:
        container_name: ics-webapp
        ports:
            - "8080:8080"
        environment:
            - "ODOO_URL=http://${HOST_IP}:8069/"
            - "PGADMIN_URL=http://${HOST_IP}:5050/"
        image: 'ehueni1982/ics-webapp:v1.0'
        networks:
            - ics_network
    postgres:
        environment:
            - POSTGRES_USER=odoo_user
            - POSTGRES_PASSWORD=odoo_password
            - POSTGRES_DB=postgres
        networks:
            - ics_network
        volumes:
            - 'pgdata:/var/lib/postgresql/data'
        container_name: postgres
        image: 'postgres:10'
        ports:
            - '5432:5432'
    odoo:
        depends_on:
            - postgres
        ports:
            - '8069:8069'
        container_name: odoo
        networks:
            - ics_network
        volumes:
            - '/data_docker/config:/etc/odoo'
            - '/data_docker/addons:/mnt/extra-addons'
            - 'odoo-web-data:/var/lib/odoo'
        environment:
            - USER=odoo_user
            - PASSWORD=odoo_password
            - HOST=postgres
        image: odoo:13.0
volumes:
    odoo-web-data:
    pgdata:
    pgadmin_data:
networks:
    ic_network:
      driver: bridge
      name: ics_network
